from sqlalchemy import Column, Integer, DateTime, String, Boolean, Float, BigInteger
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.sql import func
from sqlalchemy.types import VARCHAR
from app.core.db.session import Base


class Property(Base):
    __tablename__ = "property"
    id = Column(Integer, primary_key=True, autoincrement=True)
    full_address = Column("Full Address", String)
    longitude = Column("Longitude", Float)
    latitude = Column("Latitude", Float)
    zip = Column("Zip", BigInteger)
    rec_type = Column("REC_TYPE", String)
    pin = Column("PIN", BigInteger)
    ovacls = Column("OVACLS", BigInteger)
    class_description = Column("CLASS_DESCRIPTION", VARCHAR(255))
    current_land = Column("CURRENT_LAND", BigInteger)
    current_building = Column("CURRENT_BUILDING", BigInteger)
    current_total = Column("CURRENT_TOTAL", BigInteger)
    estimated_market_value = Column("ESTIMATED_MARKET_VALUE", BigInteger)
    prior_land = Column("PRIOR_LAND", BigInteger)
    prior_building = Column("PRIOR_BUILDING", BigInteger)
    prior_total = Column("PRIOR_TOTAL", BigInteger)
    pprior_land = Column("PPRIOR_LAND", BigInteger)
    pprior_building = Column("PPRIOR_BUILDING", BigInteger)
    pprior_total = Column("PPRIOR_TOTAL", BigInteger)
    pprior_year = Column("PPRIOR_YEAR", BigInteger)
    town = Column("TOWN", BigInteger)
    volume = Column("VOLUME", BigInteger)
    loc = Column("LOC", String)
    tax_code = Column("TAX_CODE", BigInteger)
    neighborhood = Column("NEIGHBORHOOD", BigInteger)
    houseno = Column("HOUSENO", BigInteger)
    dir = Column("DIR", String)
    street = Column("STREET", String)
    suffix = Column("SUFFIX", String)
    apt = Column("APT", String)
    city = Column("CITY", String)
    res_type = Column("RES_TYPE", String)
    bldg_use = Column("BLDG_USE", String)
    apt_desc = Column("APT_DESC", String)
    comm_units = Column("COMM_UNITS", String)
    ext_desc = Column("EXT_DESC", String)
    full_bath = Column("FULL_BATH", BigInteger)
    half_bath = Column("HALF_BATH", BigInteger)
    bsmt_desc = Column("BSMT_DESC", String)
    attic_desc = Column("ATTIC_DESC", String)
    ac = Column("AC", BigInteger)
    fireplace = Column("FIREPLACE", BigInteger)
    gar_desc = Column("GAR_DESC", String)
    age = Column("AGE", BigInteger)
    building_sq_ft = Column("BUILDING_SQ_FT", BigInteger)
    land_sq_ft = Column("LAND_SQ_FT", BigInteger)
    bldg_sf = Column("BLDG_SF", String)
    units_tot = Column("UNITS_TOT", String)
    multi_sale = Column("MULTI_SALE", BigInteger)
    deed_type = Column("DEED_TYPE", BigInteger)
    sale_date = Column("SALE_DATE", String)
    sale_amount = Column("SALE_AMOUNT", BigInteger)
    appcnt = Column("APPCNT", BigInteger)
    appeal_a = Column("APPEAL_A", BigInteger)
    appeal_a_status = Column("APPEAL_A_STATUS", String)
    appeal_a_result = Column("APPEAL_A_RESULT", String)
    appeal_a_reason = Column("APPEAL_A_REASON", BigInteger)
    appeal_a_pin_result = Column("APPEAL_A_PIN_RESULT", String)
    appeal_a_propav = Column("APPEAL_A_PROPAV", BigInteger)
    appeal_a_currav = Column("APPEAL_A_CURRAV", BigInteger)
    appeal_a_resltdate = Column("APPEAL_A_RESLTDATE", String)
    
    class Config:
        orm_mode = True
