from pydantic import BaseModel, Field, conint
from typing import Optional

class PropertySchema(BaseModel):

    full_address: str = Field(None, example="123 Main St")
    longitude: float = Field(None, example=-87.6278)
    latitude: float = Field(None, example=41.8819)
    zip: int = Field(None, example=60605)
    rec_type: str = Field(None, example="Type A")
    pin: int = Field(None, example=123456789)
    ovacls: int = Field(None, example=123)
    class_description: str = Field(None, example="Residential")
    current_land: int = Field(None, example=100000)
    current_building: int = Field(None, example=200000)
    current_total: int = Field(None, example=300000)
    estimated_market_value: int = Field(None, example=350000)
    prior_land: int = Field(None, example=90000)
    prior_building: int = Field(None, example=190000)
    prior_total: int = Field(None, example=280000)
    pprior_land: int = Field(None, example=80000)
    pprior_building: int = Field(None, example=180000)
    pprior_total: int = Field(None, example=260000)
    pprior_year: int = Field(None, example=2020)
    town: int = Field(None, example=100)
    volume: int = Field(None, example=500)
    loc: str = Field(None, example="Location Info")
    tax_code: int = Field(None, example=200)
    neighborhood: int = Field(None, example=300)
    houseno: int = Field(None, example=400)
    dir: str = Field(None, example="N")
    street: str = Field(None, example="Main")
    suffix: str = Field(None, example="St")
    apt: str = Field(None, example="101")
    city: str = Field(None, example="Chicago")
    res_type: str = Field(None, example="Residential")
    bldg_use: str = Field(None, example="Single Family")
    apt_desc: str = Field(None, example="Apartment")
    comm_units: str = Field(None, example="5")
    ext_desc: str = Field(None, example="Brick")
    full_bath: int = Field(None, example=2)
    half_bath: int = Field(None, example=1)
    bsmt_desc: str = Field(None, example="Finished")
    attic_desc: str = Field(None, example="None")
    ac: int = Field(None, example=1)
    fireplace: int = Field(None, example=1)
    gar_desc: str = Field(None, example="Detached")
    age: int = Field(None, example=20)
    building_sq_ft: int = Field(None, example=2000)
    land_sq_ft: int = Field(None, example=3000)
    bldg_sf: str = Field(None, example="2000")
    units_tot: str = Field(None, example="1")
    multi_sale: int = Field(None, example=0)
    deed_type: int = Field(None, example=1)
    sale_date: str = Field(None, example="2023-01-01")
    sale_amount: int = Field(None, example=350000)
    appcnt: int = Field(None, example=1)
    appeal_a: int = Field(None, example=1)
    appeal_a_status: str = Field(None, example="Pending")
    appeal_a_result: str = Field(None, example="Approved")
    appeal_a_reason: int = Field(None, example=1)
    appeal_a_pin_result: str = Field(None, example="Result")
    appeal_a_propav: int = Field(None, example=350000)
    appeal_a_currav: int = Field(None, example=300000)
    appeal_a_resltdate: str = Field(None, example="2023-06-01")
